In [1]:
using Pkg;

Pkg.activate(mktempdir())
Pkg.update()
Pkg.add([
    "LinearAlgebra"
])

  Activating new project at `C:\Users\79021\AppData\Local\Temp\jl_36RwHw`
    Updating registry at `C:\Users\79021\.julia\registries\General.toml`
     Project No packages added to or removed from `C:\Users\79021\AppData\Local\Temp\jl_36RwHw\Project.toml`
    Manifest No packages added to or removed from `C:\Users\79021\AppData\Local\Temp\jl_36RwHw\Manifest.toml`
   Resolving package versions...
    Updating `C:\Users\79021\AppData\Local\Temp\jl_36RwHw\Project.toml`
  [37e2e46d] + LinearAlgebra v1.12.0
    Updating `C:\Users\79021\AppData\Local\Temp\jl_36RwHw\Manifest.toml`
  [56f22d72] + Artifacts v1.11.0
  [8f399da3] + Libdl v1.11.0
  [37e2e46d] + LinearAlgebra v1.12.0
  [e66e0078] + CompilerSupportLibraries_jll v1.3.0+1
  [4536629a] + OpenBLAS_jll v0.3.29+0
  [8e850b90] + libblastrampoline_jll v5.15.0+0


In [ ]:
using LinearAlgebra

# Identity matrix

I3 = I(3)
println("Identity 3x3:")
display(Matrix(I3))

x = [2.0, 5.0, -1.0]
println("\nI* x = x: ", I3 * x == x)

3×3 Matrix{Bool}:
 1  0  0
 0  1  0
 0  0  1

2×2 Matrix{Float64}:
 4.0  7.0
 2.0  6.0

2×2 Matrix{Float64}:
  0.6  -0.7
 -0.2   0.4

Identity 3x3:

I* x = x: true

Matrix A:

Inverse A⁻¹:

A * A⁻¹ ≈ I: true


In [ ]:
# Inverse matrix
A = [4.0 7.0; 2.0 6.0]
A_inv = inv(A)

println("\nMatrix A:")
display(A)
print(A)

println("\nInverse A⁻¹:")
display(A_inv)
print(A_inv)

println("\nA * A⁻¹ ≈ I: ", A * A_inv ≈ I(2))

2×2 Matrix{Float64}:
 4.0  7.0
 2.0  6.0

2×2 Matrix{Float64}:
  0.6  -0.7
 -0.2   0.4


Matrix A:
[4.0 7.0; 2.0 6.0]
Inverse A⁻¹:
[0.6000000000000001 -0.7000000000000001; -0.2 0.4]
A * A⁻¹ ≈ I: true


In [13]:
# Solving linear system Ax = b

A = [3.0 1.0; 1.0 2.0]
b = [9.0, 8.0]

x_direct = A \ b
x_inverse = inv(A) * b

println("\nSolving Ax = b:")
println("Direct solve (A\\b): ", x_direct)
println("Via inverse: ", x_inverse)
println("Residual ∥Ax - b∥: ", norm(A * x_direct -b))


Solving Ax = b:
Direct solve (A\b): [2.0, 3.0]
Via inverse: [1.9999999999999998, 3.0]
Residual ∥Ax - b∥: 0.0


In [ ]:
# ML example: Linear regression Closed Base
# ordinary least squares in closed form using normal equations

X = [1.0 1.0; 1.0 2.0; 1.0 3.0; 1.0 4.0]
y = [2.1, 3.9, 6.1, 7.9]

w = inv(X' * X) * X' * y
println("\nLinear regression weights (closed form):")
println("w = ", w)
println("Predictions: ", X * w)




Linear regression weights (closed form):
w = [0.09999999999999432, 1.9600000000000009]
Predictions: [2.059999999999995, 4.019999999999996, 5.979999999999997, 7.939999999999998]


In [ ]:
# Numerical stability

A_nice = [1.0 0.0; 0.0 1.0]
A_bad = [1.0 1.0; 1.0 1.0 + 1e-10]

println("\nCondition numbers:")
println("Well-conditioned: ", cond(A_nice))
println("Ill-conditioned: ", cond(A_bad))


Condition numbers:
Well-conditioned: 1.0
Ill-conditioned: 3.9999947702450424e10


In [ ]:
# Task 1: Create 4x4 identity and verify I*I = I

using LinearAlgebra;

# create an identity matrix 
I4 = I(4)

# display allow to print the square matrix
display(Matrix(I4))

# vector
x = [2.3, 4.5, 8.9, 7.8]
display(x)

# This equation should be true, because each xᵢ in the equal's system has only the one solution
# The dot product for the each element is like: xᵢ * 1 = xᵢ
println("I4 = I4 * x, Result: ", x == I4 * x)



4×4 Matrix{Bool}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1

4-element Vector{Float64}:
 2.3
 4.5
 8.9
 7.8

I4 = I4 * x, Result: true


In [29]:
# Task 2: Given system:
#   2x + 3y = 8
#   x + 4y = 9
# Solve using inv() and using

# Use Ax = b equation

using LinearAlgebra;

A = [2 3; 1 4]  # equation system's coefficients
b = [8, 9]      # vector of result values
display(Matrix(input_matrix))

# Julia's operator solution
println("Julia's operator solution:")
x = A \ b
println(solution_one)

# x = A⁻¹b
println("Solution using inverted matrix x = A⁻¹b:")
x = inv(A) * b
println(x)


2×2 Matrix{Int64}:
 2  3
 1  4

Julia's operator solution:
[1.0, 2.0]
Solution using inverted matrix x = A⁻¹b:
[1.0, 2.0]


In [34]:
# Task 3: Create a singular matrix and try inv()
# What error do you get?

# SVD - Singular Value Decomposition

using LinearAlgebra;

# A is 2x3

A = [1 2 3;
    4 5 6]

display(Matrix(A))

rA = rank(A) # uses SVD internally
println("rank(A) = $rA, number of columns = ", size(A, 2))
println("Columns are linearly ", rA < size(A, 2) ? "dependent" : "independent")

# trying to invert A
# The error should be: DimensionMismatch: matrix is not square: dimensions are (2, 3)
iA = inv(A)

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

rank(A) = 2, number of columns = 3
Columns are linearly dependent


DimensionMismatch: DimensionMismatch: matrix is not square: dimensions are (2, 3)

In [40]:
# Task 4: For the linear regression example above,
# add a third feature column and solve again


x = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
y = [2.1, 3.9, 6.1, 7.9, 8.7, 6.5]

# Design matrix with 3 columns: [1, x, x²]
X = [ones(length(x)) x x.^2]

ω = inv(X' * X) * X' * y

println(w)

# ŷ = Xω
println("Predictions: ", X * ω)


[0.5799999999999983, 1.7200000000000006]
Predictions: [1.6142857142856677, 4.534285714285701, 6.540000000000017, 7.631428571428614, 7.8085714285714936, 7.071428571428655]
